name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source code
      uses: actions/checkout@v2
    - name: Login to docker registry
      uses: actions-hub/docker/login@master
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_REGISTRY_URL: docker.io
    - name: Build the Docker image
      if: success()
      run: docker build . --file Dockerfile --tag ${{ github.repository }}:latest
    - name: Push to docker hub :latest
      if: success()
      uses: actions-hub/docker@master
      with:
        args: push docker.io/${{ github.repository }}:latest
